### ISSUE TITLE
Upgrade dependency ranges

### ISSUE THREAD

**Issue by fealho** [sdv-dev/SDGym#118]
The latest versions of the `compress-pickle` and `humanfriendly` are not supported by `SDGym`:

| Library | Upper bound (unsupported) | Latest release |
|-|-|-|
| `pandas` | 1.1.5 | 1.3.1 |
| `pomegranate` | 0.14.2 | 0.14.5 |
| `compress-pickle` | 2 | 2.01 |
| `humanfriendly` | 9 | 9.2 |

We should investigate why and update the code if necessary to support them.

**Comment by katxiao** [comment]
The `pomegranate` version cap is because `py3.6` does not support the newest `pomegranate` release. We can revisit `pomegranate` once `py3.6` is officially deprecated.
