### ISSUE TITLE
Is it possible to apply tensorflow custom function?

### ISSUE THREAD

**Issue by sungreong** [sdv-dev/SDGym#12]
hello, I see `sdgym/synthesizers`.

the functions are written by PyTorch. 

I usually use TensorFlow. 
Is this package also applicable to the TensorFlow code?

and how can I save the learned model?

Thanks

**Comment by csala** [comment]
Hello @sungreong 

I'm not entirely sure about understanding you properly, but if you mean whether it is possible to use the benchmarking tool for tensorflow based synthesizers, yes, it is possible.

All you need to do is prepare your synthesizer function following the specification and pass it to the benchmark function:

```
from sdgym import benchmark
from your_package import your_tensorflow_synthesizer

def your_synthesizer_function(X, categorical_columns, ordinal_columns):
    # put the code here to use your_tensorflow_synthesizer to model and sample data
    return sampled_data

benchmark(your_synthesizer_function)
```

Please, let me know if this is what you were looking for.

**Comment by csala** [comment]
> and how can I save the learned model?

You can do so using [PyTorch save and load](https://pytorch.org/tutorials/beginner/saving_loading_models.html#save-load-entire-model)

For this, after fitting your model, you save it using:

```python
import torch

torch.save(synthesizer, '/path/to/your/model.pkl')
```

And later on load it doing:

```python
import torch

synthesizer = torch.load('/path/to/your/model.pkl')
```

**Comment by sungreong** [comment]
Thank you very much for your quick answer.
If you have time later, I think it will be helpful if you make a brief example of other frameworks such as Tensorflow and Keras.

**Oh, I have one question about TGAN paper.**
In the paper, there is a way to deal with category missing value variables, and I think it's right to do so.

But if there's no explanation in the paper about a numerical variable that can't be substituted for missing values, is there any way you can recommend it?

**Comment by csala** [comment]
This question has already been answered [here](https://github.com/sdv-dev/CTGAN/issues/39), so I'm closing this issue for now.
