### ISSUE TITLE
Boto Client Error: The provided token has expired

### ISSUE THREAD

**Issue by constant5** [sdv-dev/SDGym#122]
* SDGym version: 0.4.2.dev0
* Python version: 3.8.11
* Operating System: Windows 10

### Description

Trying to just get started running benchmarks

### What I Did

```
import sdgym 

from sdgym.synthesizers import (
    CLBN, CopulaGAN, CTGAN, Identity, Independent,
    MedGAN, PrivBN, TableGAN,
    Uniform, VEEGAN)

all_synthesizers = [
    CLBN,
    CTGAN,
    CopulaGAN,
    Identity,
    Independent,
    MedGAN,
    PrivBN,
    TableGAN,
    Uniform,
    VEEGAN,
]
scores = sdgym.run(synthesizers=all_synthesizers)
```

Exception has occurred: ClientError       (note: full exception trace is shown but execution is paused at: <module>)
An error occurred (ExpiredToken) when calling the ListObjects operation: The provided token has expired.
  File "C:\Users\crm0376\Projects\SDGym\sdgym\datasets.py", line 118, in get_available_datasets
    response = s3.list_objects(Bucket=bucket or BUCKET)
  File "C:\Users\crm0376\Projects\SDGym\sdgym\datasets.py", line 161, in get_dataset_paths
    datasets = get_available_datasets()['name'].tolist()
  File "C:\Users\crm0376\Projects\SDGym\sdgym\benchmark.py", line 321, in run
    datasets = get_dataset_paths(datasets, datasets_path, bucket, aws_key, aws_secret)
  File "C:\Users\crm0376\Projects\SDGym\testing_load.py", line 21, in <module> (Current frame)
    scores = sdgym.run(synthesizers=all_synthesizers)

**Comment by npatki** [comment]
Hello, I'm marking this issue as stale since it has been over a year. Since 2021, we have significantly improve our usage API and the functionality.

For reference, please see our [new SDGym website here](https://docs.sdv.dev/sdgym). If you are still encountering errors when running the benchmark, feel free to file a new issue. Thanks!
