### ISSUE TITLE
[TableGAN] ValueError: cannot reindex from a duplicate axis

### ISSUE THREAD

**Issue by tejuafonja** [sdv-dev/SDGym#138]
### Environment Details

Please indicate the following details about the environment in which you found the bug:

* SDGym version: 0.5.0
* Python version: 3.7.13
* Operating System: Linux (run on colab)

### Error Description
Running `sdgym.run(synthesizers=[TableGAN], datasets=["adult"], show_progress=True, iterations=1)` gives an ValueError for TableGAN synthesizer. The error seem to be triggered by `synthetic_data.update(ht.reverse_transform(sampled_data))` on line 183 in the base.py file. 

### Steps to reproduce
```
import sdgym
from sdgym.synthesizers import TableGAN
sdgym.run(synthesizers=[TableGAN], datasets=["adult"], show_progress=True, iterations=1)
```

```
sdgym.run(synthesizers=[TableGAN], datasets=["adult"], show_progress=True, iterations=1)
```

<img width="1307" alt="Screenshot 2022-03-29 at 15 59 32" src="https://user-images.githubusercontent.com/18422386/160629274-07c93126-94af-4891-b534-96581830016d.png">

You can also run [this colab ](https://colab.research.google.com/drive/1CsL-1ifz04ikIafFcPCxlnqVQk0fw27m?usp=sharing) notebook to reproduce the error.

**Comment by npatki** [comment]
Hi @tejuafonja, thank you for providing the details and Colab notebook.

In the most recent version of SDGym (0.6.0), we have been focused on streamlining our usage and providing a robust benchmarking framework. We are prioritizing the synthesizers from the [SDV library](https://docs.sdv.dev/sdv) as well as providing you the ability to [easily include your own, custom synthesizer](https://docs.sdv.dev/sdgym/customization/synthesizers/custom-synthesizers).

So unfortunately, the SDGym is not offering or guaranteeing support for the `TableGAN` synthesizer. Is this something you need? We can consider turning this issue into a feature request for it. To help us prioritize, it would be helpful to understand your use case and the importance of this synthesizer.

**Comment by npatki** [comment]
I'm closing this issue off since it has been inactive for some time. Please feel free to reply if there is more to discuss and we can always reopen the issue to investigate.

Alternatively, you are welcome to file a new feature request for adding in`TableGAN`. We prioritize new requests by demand and importance to your project, so any other information about your usage would be helpful. Thanks.

**Comment by tejuafonja** [comment]
Hi @npatki, apologies for my delayed response. Indeed, this is no longer needed. I fixed the bug locally and was able to benchmark the method in one of my papers by adapting the code provided via SDGym -- thanks to your team.
