### ISSUE TITLE
PrivBNSynthesizer missing privbayes.bin file

### ISSUE THREAD

**Issue by wwymak** [sdv-dev/SDGym#15]
the demo `PrivBNSynthesizer` is looking for a file `privbayes/privBayes.bin` on https://github.com/DAI-Lab/SDGym/blob/aa2b82b2a68e9d0391ea67704b4b058cad867512/sdgym/synthesizers/privbn.py#L21, but in my local install (via `pip install sdgym` in conda env, macos), this file does not exist. Is this supposed to be generated during the install? Or do I need to do an extra steps to get this file?

**Comment by csala** [comment]
Hi @wwymak 

In order to be able to use the `PrivBNSynthesizer` you need to compile the C dependencies.

You can see the instructions here: https://github.com/DAI-Lab/SDGym#compile-c-dependencies

**Comment by csala** [comment]
> You can see the instructions here: https://github.com/DAI-Lab/SDGym#compile-c-dependencies

Bear in mind that in order to be able to run this installing using `pip install sdgym` is not enough. You will need to have cloned or downloaded the repository, otherwise the `make compile` command will fail.

**Comment by csala** [comment]
Closing this for now, as the question seems answered.

Please feel free to reopen the issue if there is any follow up question.
