### ISSUE TITLE
Pip encounters dependency issues with `ipython`

### ISSUE THREAD

**Issue by npatki** [sdv-dev/SDGym#187]
### Environment Details

Please indicate the following details about the environment in which you found the bug:

* SDGym version: 0.8.0 (version in development)
* Python version: 3.8
* Operating System: Linux, iPython notebook

### Error Description

When installing sdgym with `pip`, I see a dependency error with `ipython`.

```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
ipython 7.9.0 requires jedi>=0.10, which is not installed.
cvxpy 1.2.3 requires setuptools<=64.0.2, but you have setuptools 66.0.0 which is incompatible.
aiohttp 3.8.3 requires charset-normalizer<3.0,>=2.0, but you have charset-normalizer 3.0.1 which is incompatible.
```

### Steps to reproduce

Reproduce this by installing the in-development version in an iPython notebook (eg. Google Colab)

**Comment by katxiao** [comment]
This only seems to be an issue when installing directly from GitHub - it's fixed in the newest pre-release.
