### ISSUE TITLE
`FileNotFoundError` when saving an SDV model in the same environment

### ISSUE THREAD

**Issue by npatki** [sdv-dev/SDGym#189]
### Environment Details

* SDGym version: 0.8.0 (under development)
* Python version: 3.8
* Operating System: Linux (Colab Notebook)

### Error Description
The SDV library is a dependency for SDGym. I have confirmed the installed SDV version is the latest -- `0.17.2`. However, I am unable to use all of the SDV functionality. In particular, the `model.save` function leads to an error.

Note: I have confirmed that the `save` functionality works if I install SDV alone in a fresh environment. The issue seems to be when it's installed in the same environment as SDGym. It may have something to do with general installation issues (see #187)

### Steps to reproduce

Install SDGym in a fresh environment. Then try to create and save an SDV model.

```python
from sdv.tabular import GaussianCopula
from sdv.demo import load_tabular_demo

metadata, data = load_tabular_demo('student_placements_pii', metadata=True)
model = GaussianCopula(table_metadata=metadata)
model.fit(data)
synthetic_data = model.sample(5)
model.save('model.pkl')
```

**Comment by katxiao** [comment]
This seems to be resolved by the dependency & Python version upgrades in #170
