### ISSUE TITLE
TypeError: '(slice(None, None, None), 0)' is an invalid key when using SDGYM synthesizers on locally stored data files

### ISSUE THREAD

**Issue by abedshantti** [sdv-dev/SDGym#209]
* SDGym version: 0.6.0
* Python version: 3.10.10
* Operating System: Windows10 x64

### Description

There seems to be an issue with transforming a dataframe when using the available standard SDGYM synthesizers. The problem appears to be with slicing a dataframe using df[:, idx], which returns a InvalidIndexError: (slice(None, None, None), 0) error. 

https://github.com/sdv-dev/SDGym/blob/fee990c54eb0a1374a300007c4762e2a3001a059/sdgym/synthesizers/utils.py#L138

For me it looks like the function above should use .loc or .iloc. 

Otherwise, the transformation function in https://github.com/sdv-dev/SDGym/blob/fee990c54eb0a1374a300007c4762e2a3001a059/sdgym/synthesizers/medgan.py#L156

should be changed from:

`self.transformer.fit(data, categorical_columns, ordinal_columns)`

into

`self.transformer.fit(data.values, categorical_columns, ordinal_columns)`

### What I Did

```python
from sdgym.synthesizers import MedGANSynthesizer
model = MedGANSynthesizer()
train_data = pd.read_csv("adult_train.csv",  header = 0) #adult_train is stored locally on my device
catg_cols = ['workclass', 'education', 'marital-status', 'occupation', 'relationship', 'race', 'sex', 'native-country', 'income']
model.fit(train_data, categorical_columns = catg_cols)
```

and I got the following output 
````
TypeError: '(slice(None, None, None), 0)' is an invalid key

During handling of the above exception, another exception occurred:

InvalidIndexError                         Traceback (most recent call last)
Cell In[18], line 1
----> 1 model.fit(train_data, categorical_columns = tuple(catg_cols))

File [~\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sdgym\synthesizers\medgan.py:157](https://_/_/~/AppData/Local/Packages/PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0/LocalCache/local-packages/Python310/site-packages/sdgym/synthesizers/medgan.py:157), in MedGANSynthesizer.fit(self, data, categorical_columns, ordinal_columns)
    155 self.transformer = GeneralTransformer()
    156 self.transformer.fit(data, categorical_columns, ordinal_columns)
--> 157 data = self.transformer.transform(data)
    158 dataset = TensorDataset(torch.from_numpy(data.astype('float32')).to(self.device))
    159 loader = DataLoader(dataset, batch_size=self.batch_size, shuffle=True, drop_last=True)
...
   5966         # if key is not a scalar, directly raise an error (the code below
   5967         # would convert to numpy arrays and raise later any way) - GH29926
-> 5968         raise InvalidIndexError(key)

InvalidIndexError: (slice(None, None, None), 0)
````

**Comment by npatki** [comment]
Hi @abedshantti, thanks for filing this issue.

When using the latest version of SDGym, I would recommend referring to our [updated documentation website](https://docs.sdv.dev/sdgym). 

We are not officially supporting the `MedGAN` synthesizer as of `0.6.0`. (See the [synthesizers user guide](https://docs.sdv.dev/sdgym/customization/synthesizers) for a list of supported synthesizers.) -- so I am not surprised that there is an error.

Would you like us to add support for `MedGAN` in future iterations? If so, we can treat this as a feature request specifically for it. To help us prioritize it, it would be helpful if you could provide more details about your use case.

**Comment by npatki** [comment]
Hello, I'm closing off this issue since it has been inactive for some time. Please feel free to reply if there is more to discuss and we can always reopen the issue.

Alternatively, you are welcome to file a new feature request for adding in `MedGAN`. We prioritize new requests by demand and importance to your project, so any other information about your usage would be helpful. Thanks.
