### ISSUE TITLE
Make `benchmark_single_table` fault-tolerant

### ISSUE THREAD

**Issue by fealho** [sdv-dev/SDGym#219]
`benchmark_single_table` should be fault-tolerant. If any part of the code doesn't run - validating, fitting, sampling, scoring - it should catch the error and add a `nan` to the output file, as is described in the [docs](https://docs.sdv.dev/sdgym/benchmarking/interpreting-results#errors).

This partially addresses issue #216.

**Comment by frances-h** [comment]
Closing because `benchmark_single_table` is currently fault tolerant. Errors and stack traces are caught, logged, and printed to stdout.
