### ISSUE TITLE
Need Help on benchmark function for real data

### ISSUE THREAD

**Issue by ArupDukeBanerjee** [sdv-dev/SDGym#23]
benchmark function requires a my_synthesizer_function which takes input real data, categorical, ordinal features and make output of synthesized data. Though the documentation provided is not sufficient for a novice like me and hence facing issue in implementing and moreover in benchmark function it's showing up that it is taking data from predefined defult_datasets which has its own metdata file stored in server in json format, hence not allowing me to benchmark on my data as I don't have metadata ready for my data sets, there are quite a few and they are large.

so any detailed documentation on how to use this benchmark function more efficiently will be helpful.
Thanks a lot for such a beautiful package. 
I am new to this domain

**Comment by csala** [comment]
Hi @ArupDukeBanerjee at the moment SDGym is not intended to be used with your own dataset, but rather to only evaluate and compare the performance of data synthesis methods over a set of well-known datasets.

For the scenario that you mention, we are working on a separated package called SDMetrics that will be made public in the upcoming days.

**Comment by ArupDukeBanerjee** [comment]
Thanks a lot for your reply. Actually I was working on Synthetic data
generation And was exploring bayesian nets or tgan or so. Then I came to
know about the CTGan package.

But the problem became when I was asked to validate the synthetic data....

I was trying to validate using KL divergence and many classifiers.

I needed a metrics of benchmarking and finally found this package which is
brilliant which has many data generator but with one problem which you have
stated just.

Can you at least tell me the guideline to have something quick and dirty
solution as validation .


Thanks a lot
Arup

**Comment by ArupDukeBanerjee** [comment]
Hi @csala 
I just wanted to know one thing about this package. Can it be used for only data generation for real data as you already stated benchmark is yet to come, meanwhile can I use/leverage different generators on my own set of data. Thanks a lot in advance!

Thanks,
Arup

**Comment by csala** [comment]
@ArupDukeBanerjee Yes, SDGym synthesizers can be used for modeling and sampling your own data, but this is just a secondary effect of having all the synthesizers here implemented with a uniform API.

I would rather recommend you to use the [CTGAN](/sdv-dev/CTGAN) package, which is simpler to use and will give you better results in the long term, since it is an actively maintained package with ease of use and sampling quality in mind while SDGym's goal is only to provide benchmark.

**Comment by ArupDukeBanerjee** [comment]
Hi Carles,
Thanks a lot for replying to me. I got your point on benchmarking and
also CTGAN is a great package, but while my *data has missing values, it
throws errors*. As a part of realistic data generation missing values is
also something that needs to be handled. Having said that I mean to say I
intend to generate a realistic missing values in my synthetic data, which I
believe is not there in CTGAN package. It would be great if you please let
me know about the resolution of missing data handling.

Thanks a lot!

Regards,
Arup
