### ISSUE TITLE
Fix typos in the docs

### ISSUE THREAD

**Issue by R-Palazzo** [sdv-dev/SDGym#264]
### Problem Description

In this [page](https://docs.sdv.dev/sdgym/benchmarking/running-a-benchmark) of the docs some typos should be fixed:
- GaussianCopulaSynthesizer instead of GaussianCouplaSynthesizer
- 'FastMLPreset' instead of 'FASTMLPreset'

**Comment by npatki** [comment]
This should now be fixed. Please file additional issues if you notice any other issues in the docs.
