### ISSUE TITLE
Failing for custom dataset

### ISSUE THREAD

**Issue by UthsavShetty** [sdv-dev/SDGym#27]
![image](https://user-images.githubusercontent.com/47194856/77592713-2bc47a80-6ec9-11ea-91bb-eea2bf102237.png)
This is the error message that we get while using the evaluation function to get the scores. The command that we use is: scores = evaluate(train, test, sampled, meta)
Synthesizer being used: UniformSynthesizer
![image (1)](https://user-images.githubusercontent.com/47194856/77592768-47c81c00-6ec9-11ea-8f3a-490b10ee48d2.png)

This error is for IndependentSynthesizer

I'm facing some issues when I use a custom dataset. Can you help me with this?

**Comment by leix28** [comment]
Hi @UthsavShetty,

This issue is probably caused by an incorrect metadata configuration. Are you able to share more details about your data and metadata so we can help.

**Comment by csala** [comment]
Closing the issue due to inactivity. Please feel free to re-open if further details can be provided.
