### ISSUE TITLE
Anyway to generate JSON structure and npy files in the required format for other datasets..

### ISSUE THREAD

**Issue by Harsha2075** [sdv-dev/SDGym#30]
Thank you very much for your prompt response for intrusion dataset. I was wondering if you have any script to generate the JSON structure file and npy file for any given dataset. Were the JSON files of the datasets used for benchmarking hand-annotated? It would be great if you can share the script if you used one, it will help in benchmarking various datasets. Thank you.

**Comment by csala** [comment]
SDGym has been updated to work with the SDV Datasets. Please check the [SDV Metadata User Guide](https://sdv.dev/SDV/user_guides/relational/relational_metadata.html) for further details.
