### ISSUE TITLE
ConvergenceWarning: Initialization 1 did not converge

### ISSUE THREAD

**Issue by AshiakerWang** [sdv-dev/SDGym#44]
* SDGym version: sdgym == 0.2.1
* Python version: Python ==3.6.10
* Operating System: Windows 10

### Description

Thanks very much for open-sourcing the code.

While running the script provided in the [benchmarking documentation](https://github.com/sdv-dev/SDGym/blob/master/SYNTHESIZERS.md) as follows:

`from sdgym import benchmark`
`from sdgym.synthesizers import CTGANSynthesizer`
`leaderboard = benchmark(synthesizers=CTGANSynthesizer)`

I encountered the following ConvergenceWaring:

`ConvergenceWarning: Initialization 1 did not converge. Try different init parameters, or increase max_iter, tol or check for degenerate data.% (init + 1), ConvergenceWarning)`

![dd](https://user-images.githubusercontent.com/14258909/86243667-5a917180-bbd9-11ea-9d16-0369eaa9a33d.png)

Could you please tell me whether is it OK to ignore the ConvergenceWaring above ? Or give me some other suggestions?
Thank you in advance！

**Comment by csala** [comment]
Hello @AshiakerWang 

This warning is normal and happens randomly. You can safely ignore it.

**Comment by AshiakerWang** [comment]
> Hello @AshiakerWang
> 
> This warning is normal and happens randomly. You can safely ignore it.

Thank you very much for your reply!
