### ISSUE TITLE
Benchmark scores function, adding other dataset, adding external synthesizer

### ISSUE THREAD

**Issue by louispaban** [sdv-dev/SDGym#47]
* SDGym version: last one 
* Python version: 3.7 
* Operating System: mac

I am trying to execute this code : 

import sdgym
from sdgym import benchmark
from sdgym.synthesizers import (
    CTGANSynthesizer, TVAESynthesizer)

all_synthesizers = [
    CTGANSynthesizer,
    TVAESynthesizer
]
scores = benchmark(synthesizers=all_synthesizers)

- Is this normal that it takes a lot of time ? Do you have tips to make it faster ? 

- And how can I add another dataset, imagine I have data.csv in my directory, how can I add it in benchmark function ? or how can I add only real datasets (from your examples)

- How can I add another synthesizer in benchmark function when the synthesizer is a python package (ex: DataSynthesizer) 

Thank you for you help !

**Comment by csala** [comment]
Hello @louispaban 

> * Is this normal that it takes a lot of time ? Do you have tips to make it faster ?
> *

Yes, it does take a lot of time. Are you running them in a CUDA-enabled system?

> * And how can I add another dataset, imagine I have data.csv in my directory, how can I add it in benchmark function ? or how can I add only real datasets (from your examples)

The initial intention of SDGym was to benchmark and compare synthesizers on a collection of well-known datasets, so using your own dataset is not really supported. For this (evaluating your own dataset), please have a look at [SDMetrics](/sdv-dev/SDMetrics) and [SDV](/sdv-dev/SDV)

> * How can I add another synthesizer in benchmark function when the synthesizer is a python package (ex: DataSynthesizer)

You can find instructions about how to write your own `synthesizer_function` (which sould wrap around DataSynthesizer) in the [SYNTHESIZERS](https://github.com/sdv-dev/SDGym/blob/master/SYNTHESIZERS.md) documentation.

To simplify, all you need to do is to wrap your synthesizer in a simple function that gets the real data as input and returns the synthetic data:

```python
from sdgym import benchmark

def my_synthesizer_function(real_data, categorical_columns, ordinal_columns):
    ...
    # Here you put your own code to use DataSynthesizer and generate synthetic_data
    ...
    return synthetic_data

scores = benchmark(synthesizers=my_synthesizer_function)
```
