### ISSUE TITLE
Track execution times and report variation

### ISSUE THREAD

**Issue by sbrugman** [sdv-dev/SDGym#49]
The leaderboard could be extended to keep track of execution times of the synthesizers and report the variation of the measurements (by default the three iterations). 

To some users, the execution time is an informative measure for evaluating the feasibility of using that synthesizer due to resource limitations (and also interesting in general). Reporting the variation for the measurements is necessary to be able compare synthesizers.

**Comment by csala** [comment]
Some of the changes introduced in #61 include model execution and metric time logging, so this can be closed.
