### ISSUE TITLE
Unable to list all the datasets available in sdgym

### ISSUE THREAD

**Issue by sudarshan-koirala** [sdv-dev/SDGym#70]
* SDGym version: 0.3.0
* Python version: 3.6 and 3.7
* Operating System: Ubuntu 18.04.5 LTS

### Description
* Issue in displaying all the datasets available in sdgym.
* The problem was discussed in slack with csala. The link for the discussion in the slack is [here](https://sdv-space.slack.com/archives/C017NHAK7CH/p1614157628001100)

**Comment by fealho** [comment]
Hi @sudarshan-koirala, this issue seems to have been fixed in the latest version of `SDGym`. Feel free to reopen the issue if you are still facing any problems.
