### ISSUE TITLE
Collect cached results from s3 bucket

### ISSUE THREAD

**Issue by katxiao** [sdv-dev/SDGym#85]
* SDGym version: 0.3.0

### Description
In issue #79 we added a way to collect results from a collection of intermediate cached results to a single scores CSV file.

It should also be possible to read the intermediate cached results from an S3 bucket, and to store the results csv to a S3 bucket. 

Python:

```python
sdgym.collect.collect_results(input_path='s3://my-bucket/path/to/results', output_file='s3://my-bucket/path/to/my/results.csv')
```

CLI

```bash
sdgym collect ... -i s3://my-bucket/path/to/results -o s3://my-bucket/path/to/my/results.csv
```

If the bucket is private, the AWS key and secret introduce in PR #74 should be used.

**Comment by csala** [comment]
Closed via #84
